### ISSUE TITLE
Expected array, received object

### ISSUE THREAD

**Issue by MMore** [kviklet/kviklet#107]
Hey,

not quite sure what happened... I tried it with a bunch of people. First it was working, so one could access a database. Another one tried and he just get a loading spinner. In the console you have sth like this:

```
Uncaught (in promise) ZodError: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "object",
    "path": [],
    "message": "Expected array, received object"
  }
]
    ul http://access.internal/assets/index-76ccce61.js:68
    get error http://access.internal/assets/index-76ccce61.js:68
    parse http://access.internal/assets/index-76ccce61.js:68
    tEe http://access.internal/assets/index-76ccce61.js:844
```

server log
```
[...]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter.doFilterInternal(OAuth2AuthorizationRequestRedirectFilter.java:181) ~[spring-security-oauth2-client-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:153) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.1.2.jar!/:6.1.2]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:143) ~[spring-session-core-3.1.1.jar!/:3.1.1]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82) ~[spring-session-core-3.1.1.jar!/:3.1.1]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.11.jar!/:6.0.11]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.11.jar!/:na]
2024-05-14T10:14:11Z app[e82ddd1b0d12d8] fra [info]	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

I changed the Developer role in between, maybe that's why. 
That's the current config
<img width="553" alt="Screenshot 2024-05-14 at 12 18 31" src="https://github.com/kviklet/kviklet/assets/172760/61497dac-55ad-468f-a238-7ab58eddf65d">

People deleted cookies and signed in again after I changed the role. Any ideas?

**Comment by Askir** [comment]
Hmm, it looks like something with the Role editing isn't really working the DATASOURCE permission strings are in the wrong format. I haven't tried this in a long time since I planned to build a new interface anyways for v0.4.

Do you have direct access to the underlying kviklet db? in the policy table has to be an entry with `datasource_connection:get`, it missing is probably the root cause for your issue.

These are the default permissions for the developer role:
```
datasource_connection:get
execution_request:get
execution_request:edit
execution_request:execute
user:get
user:edit
```

Everything with `*` as resource/scope. No worries the `user:get` and `user:edit` just means edit their own user even with `*`, there is separate permissions for editing other users. And they can't change their role of course.

If you want to restrict e.g. execution-request creation to specific connections you can change the `*` out for a connection id. It will all be a bit more clear in the next version I hope.

I will try to get a fix out for this asap but I am actually out traveling until next monday and am unlikely to have enough time to do it until then sorry :(

Thank you very much for raising it though, I hope you can fix it by manually editing the DB for now.

**Comment by MMore** [comment]
Thanks, that's already very helpful, DB works!

**Comment by Askir** [comment]
<img width="1095" alt="Screenshot 2024-05-24 at 13 02 15" src="https://github.com/kviklet/kviklet/assets/10251955/ce5ce7fc-0f75-43b8-b0a4-644762ec1b13">
FYI I just merged some more robust role creation and editing.
