### ISSUE TITLE
Connection Policy doesn't work

### ISSUE THREAD

**Issue by sapisuper** [kviklet/kviklet#140]
Hi, 

I create new role (Role DEV C) with specified connection policy to access the database (ex : Database C). But when I try to create request query or request temporary to Database C with new Role Dev C the request not created and I got this error 

    2024-06-12T08:51:34.335Z ERROR 8 --- [nio-8080-exec-2] d.k.k.c.ExceptionHandlerController       : Access denied at /execution-requests/

    org.springframework.security.access.AccessDeniedException: Access Denied
	at dev.kviklet.kviklet.security.AuthorizationManagerInterceptor.attemptPreAuthorization(MethodSecurityConfiguration.kt:223) ~[classes!/:0.0.1-SNAPSHOT]
	at dev.kviklet.kviklet.security.AuthorizationManagerInterceptor.invoke(MethodSecurityConfiguration.kt:175) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.11.jar!/:6.0.11]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756) ~[spring-aop-6.0.11.jar!/:6.0.11]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.11.jar!/:6.0.11]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[spring-tx-6.0.11.jar!/:6.0.11]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.11.jar!/:6.0.11]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.11.jar!/:6.0.11]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756) ~[spring-aop-6.0.11.jar!/:6.0.11]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-6.0.11.jar!/:6.0.11]
	at dev.kviklet.kviklet.service.ExecutionRequestService$$SpringCGLIB$$0.create(<generated>) ~[classes!/:0.0.1-SNAPSHOT]
	at dev.kviklet.kviklet.controller.ExecutionRequestController.create(ExecutionRequestController.kt:555) ~[classes!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)

**Comment by Askir** [comment]
You're right there is a bug in the permissions system here. Working on a fix should get it done by end of today I hope.

**Comment by Askir** [comment]
I think #143 fixes this, but I'll do some more tests before releasing it as 0.4.1

**Comment by sapisuper** [comment]
@Askir good, let me try. Thank you

**Comment by sapisuper** [comment]
@Askir I just try with version 0.4.1 is work smooth 👍 

closed this issue. thanks
